#Exercise 1
## Part1

In [1]:
from sklearn.datasets import load_wine

# Load the wine dataset
wine_data = load_wine()

# Print the description of the dataset
print(wine_data.DESCR)

# Access the features (X) and target (y) variables
X = wine_data.data  # Features
y = wine_data.target  # Target variable

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            10.6  30.0    19.5   3.3
    Ma

In [2]:
target1=y.tolist()
my_set=set(target1)
target_list=list(my_set)

if 0 in target_list:
    print(f"The classes are from (0,1,2,.......C-1)")
else:
    print(f"The classes are from (1,2,3,.......C)")

The classes are from (0,1,2,.......C-1)


##Part 2

In [3]:
transformed_label=[1]*len(wine_data.data)
for i in range(len(y)):
  if y[i]!=1:
    transformed_label[i]=-1
transformed_label

[-1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1]

## Part 3

In [4]:
#Normalising the columns of A
A=wine_data.data
import numpy as np



# Normalize the columns of A
min_vals = np.min(A, axis=0)  # Minimum values of each column
max_vals = np.max(A, axis=0)  # Maximum values of each column

# Min-Max normalization
A_normalized = -1 + 2 * ((A - min_vals) / (max_vals - min_vals))

print("Original matrix A:")
print(A)
print("\nNormalized matrix A:")
print(A_normalized)

Original matrix A:
[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]

Normalized matrix A:
[[ 0.68421053 -0.61660079  0.14438503 ... -0.08943089  0.94139194
   0.12268188]
 [ 0.14210526 -0.58893281 -0.1657754  ... -0.07317073  0.56043956
   0.10128388]
 [ 0.12105263 -0.35968379  0.40106952 ... -0.10569106  0.39194139
   0.29386591]
 ...
 [ 0.17894737  0.39920949 -0.03743316 ... -0.82113821 -0.78754579
  -0.20542083]
 [ 0.12631579 -0.2687747   0.0802139  ... -0.80487805 -0.74358974
  -0.19828816]
 [ 0.63157895  0.32806324  0.47593583 ... -0.78861789 -0.75824176
  -0.59771755]]


## Part 4

In [5]:
import random
index_array=[i for i in range(len(wine_data.data))]
for i in range(178):
  random.shuffle(index_array)
train_size=int(0.8*len(index_array)) # Use first 80 percent of the index for trainining examples and rest for testing examples
train_index=index_array[:train_size]
test_index=index_array[train_size:]
train_data1=[A[i] for i in train_index]
test_data1=[A[i] for i in test_index]
train_data=np.array(train_data1)
test_data=np.array(test_data1)
train_label1=[transformed_label[i] for i in train_index]
train_label=np.array(train_label1)
test_label1=[transformed_label[i] for i in test_index]
test_label=np.array(test_label1)


In [6]:
print("Training data is")
print(train_data)
print("Testing data is:")
print(test_data)
print("Training labels Are")
print(train_label)
print("Testing labels are:")
print(test_label)

Training data is
[[1.299e+01 1.670e+00 2.600e+00 ... 1.310e+00 3.500e+00 9.850e+02]
 [1.141e+01 7.400e-01 2.500e+00 ... 1.100e+00 2.310e+00 4.340e+02]
 [1.165e+01 1.670e+00 2.620e+00 ... 1.360e+00 3.210e+00 5.620e+02]
 ...
 [1.324e+01 2.590e+00 2.870e+00 ... 1.040e+00 2.930e+00 7.350e+02]
 [1.475e+01 1.730e+00 2.390e+00 ... 1.250e+00 2.730e+00 1.150e+03]
 [1.233e+01 1.100e+00 2.280e+00 ... 1.250e+00 1.670e+00 6.800e+02]]
Testing data is:
[[1.233e+01 9.900e-01 1.950e+00 1.480e+01 1.360e+02 1.900e+00 1.850e+00
  3.500e-01 2.760e+00 3.400e+00 1.060e+00 2.310e+00 7.500e+02]
 [1.145e+01 2.400e+00 2.420e+00 2.000e+01 9.600e+01 2.900e+00 2.790e+00
  3.200e-01 1.830e+00 3.250e+00 8.000e-01 3.390e+00 6.250e+02]
 [1.351e+01 1.800e+00 2.650e+00 1.900e+01 1.100e+02 2.350e+00 2.530e+00
  2.900e-01 1.540e+00 4.200e+00 1.100e+00 2.870e+00 1.095e+03]
 [1.237e+01 9.400e-01 1.360e+00 1.060e+01 8.800e+01 1.980e+00 5.700e-01
  2.800e-01 4.200e-01 1.950e+00 1.050e+00 1.820e+00 5.200e+02]
 [1.225e+01 1.730e

## Part 5

In [7]:
def prediction_function(w,x):
  if w.T@x>0:
    pred=1
  elif w.T@x<0:
    pred=-1
  return pred

## Part 6

In [8]:
def accuracy(model_w,data,label):
  k=0
  n=len(data)
  for i in range(n):
    val=prediction_function(w,data[i])
    if val==label[i]:
      k+=1
  accur=float((k/n)*100)
  return accur